### ISSUE TITLE
FcmSharp.Exceptions.FcmMessageException was thrown without any details provided

### ISSUE THREAD

**Issue by yar1k0v** [bytefish/FcmSharp#10]
I got this exception but can't find a reason for it.

**Comment by bytefish** [comment]
Please add some code to reproduce the issue.

**Comment by astalegale** [comment]
Hi, i was able to reproduce the error.

If you write a wrong project in FileBasedFcmClientSettings.CreateFromFile the library will throw the above exception without a clear error message.


Regards
Alex

**Comment by bytefish** [comment]
@astalegale @yar1k0v I have added an error message, so you don't need to read the Error Object included in the response to have a quick look at what's the problem. The message is just the JSON Content, that came back from the server and it should explain the error as detailed as possible. I will release a new version as soon as Issue #12 has been fixed.

**Comment by bytefish** [comment]
Better error messaging is now in Release 2.2.0.
