### ISSUE TITLE
In Message class change Dictionary<string, string> to Dictionary<string, object> to allow nested objects

### ISSUE THREAD

**Issue by yar1k0v** [bytefish/FcmSharp#11]
Right now it's not convenient to send a message with nested objects.

**Comment by bytefish** [comment]
The Protocol mandates, that data are Key Value Pairs of Strings, please see:

* https://firebase.google.com/docs/reference/fcm/rest/v1/projects.messages

It is also, what's implemented in the official Java Admin SDK:

* https://github.com/firebase/firebase-admin-java/blob/master/src/main/java/com/google/firebase/messaging/Message.java

If an additional abstraction layer is needed, you could easily turn an object into a Dictionary with Newtonsoft JSON and then pass it into the message.
