### ISSUE TITLE
Invalid JSON payload received. Unknown name "aps" at 'message.apns': Cannot find field.

### ISSUE THREAD

**Issue by smikaello** [bytefish/FcmSharp#12]
If I add the Aps instanse into ApnsConfig in the message, I receive this error (error text is taken from FcmMessageException.Errors). No metter what content is inside the Aps, it fails every time. Please take a look.

**Comment by bytefish** [comment]
That's clearly a bug. I will fix it.

**Comment by bytefish** [comment]
I have just pushed a Fix. Can you let me know, if it works for you?

**Comment by bytefish** [comment]
Right now it is only in the Solution, so you probably have to check it out and compile a DLL. If you don't know how to do it, I will just release a new Version to NuGet. But it would be great if you check, that the Bugfix resolves the issue.

**Comment by bytefish** [comment]
@smikaello I have released Version 2.2.0 to NuGet. Please let me know, if it fixes the problem.

**Comment by bytefish** [comment]
I actually misread the structure and accidentally forgot the ``payload`` field in the ``ApnsConfig``. That's why the error was thrown. Better Unit Testing should catch it, but I don't have the test data yet. Feel free to add a test, if your integration test was successful.

**Comment by bytefish** [comment]
Please reopen the Ticket, if the error still occurs.

**Comment by smikaello** [comment]
Thanks for the quick reply and fix, it works now.
