### ISSUE TITLE
Badge in Aps class should be int

### ISSUE THREAD

**Issue by asakuraa** [bytefish/FcmSharp#16]
From [Payload Key Reference](https://developer.apple.com/library/archive/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/PayloadKeyReference.html#//apple_ref/doc/uid/TP40008194-CH17-SW1) Badge in Aps class should be int instead of string.

**Comment by bytefish** [comment]
Thanks for your Pull Request. I will create a new release and upload it to NuGet this evening.

**Comment by bytefish** [comment]
Released Version 2.3.1 to NuGet, which fixes the issue. Please reopen if the problem persists.
