### ISSUE TITLE
Nothing happens after sending the notification

### ISSUE THREAD

**Issue by allistoncarlos** [bytefish/FcmSharp#19]
My iOS app is configured with Firebase, and I can send notifications using the console, but when I try to send using the backend, nothing happens...

Here's my code:

var settings = FileBasedFcmClientSettings.CreateFromFile(project, credentialsFileName);

            using (var client = new FcmClient(settings))
            {
                var data = notification.ToDictionary();

                var message = new FcmMessage
                {
                    ValidateOnly = false,
                    Message = new Message
                    {
                        // { "body": "Test", "Title": "Testing" }
                        Data = data,
                        Topic = "all-topic"
                    }
                };

                var cts = new CancellationTokenSource();

                var result = client.SendAsync(message, cts.Token).GetAwaiter().GetResult();
            }

The code returns the following string, but the notification doesn't arrive in the App:
"projects/projectId/messages/7043580007032901484"

What am I missing?

**Comment by bytefish** [comment]
Well, that's hard to say. Which Console do you refer to? The Firebase Console? Apparently the message was sent successfully, because you get a Message ID back and no error is returned. So I wouldn't say it is a bug in the library.

**Comment by bytefish** [comment]
Did you also try to send a notification? Are these received?

**Comment by bytefish** [comment]
@allistoncarlos Could you go through this one: https://firebase.googleblog.com/2017/01/debugging-firebase-cloud-messaging-on.html? Maybe it has some useful information on how to debug the problem.

**Comment by bytefish** [comment]
@allistoncarlos You are using the Data Property. You have to use the Notification Property for sending a Notification: 

https://github.com/bytefish/FcmSharp/blob/bef4cac6d49e02ec091cf8923bf7ed800eb10466/FcmSharp/FcmSharp/Requests/Message.cs#L15

Then it will work correctly.

**Comment by allistoncarlos** [comment]
Thanks! It's fully working now :D

**Comment by bytefish** [comment]
Great! Thanks for the feedback.
