### ISSUE TITLE
only work for android? or work on ios also ?

### ISSUE THREAD

**Issue by teamsmiley** [bytefish/FcmSharp#21]
just question 
it only work for android? or work on ios also ?

**Comment by bytefish** [comment]
This project is the implementation of the Firebase HTTP API:

* https://firebase.google.com/docs/reference/fcm/rest/v1/projects.messages

The API allows to send Push Messages to Android and iOS Devices of course. You can find a documentation of Firebase Cloud Messaging here: 

* https://firebase.google.com/docs/cloud-messaging/
