### ISSUE TITLE
Data Payload Should be Object, not Dictionary<string, string>

### ISSUE THREAD

**Issue by oliverkane** [bytefish/FcmSharp#23]
In the object called Message, there's a property called Data. This is used to send arbitrary JSON allowable information in the body of the message.  Currently, this requires using the type Dictionary<string, string>, rather than Object.  This imposes limitations on the type of information that can be sent.  For example, Let's say I want to send:

```
var data = new {
   prop1 = "This can be done in a dictionary" 
   prop2 = new {
        nestedProp = "This cannot"
   }
}
```
Please consider modifying this library so that it doesn't require the Dictionary<string, string> type, but allows any JSON serializable Object.

**Comment by bytefish** [comment]
As I read the Google APIs it is a String map. Can you point me to an official API documentation, that shows the Payload can contain nested data? The official Firebase Java SDK also imposes this limitation.

**Comment by oliverkane** [comment]
You are most correct. I embarrassingly withdraw my PR.

**Comment by bytefish** [comment]
No reason to be embarrassed! 😮 I would have expected complex objects, too. And maybe it is possible to send the objects, but it's just that their official client doesn't do it, so I didn't want to do it initially. I was hoping for a document, because I hate this limitation, too.
