### ISSUE TITLE
Thread was being aborted on initialize FCMClient

### ISSUE THREAD

**Issue by rex232** [bytefish/FcmSharp#26]
Hi, when i init FCMclient and it has error for [Thread was being aborted.]. The setting file is load correctly, any advise ? thanks

            var settings = FileBasedFcmClientSettings.CreateFromFile("XXXXX", string.Format(@"{0}\Config\{1}", sSystemPath, "googleserviceaccountkey.json"));
            try
            {
                var client4 = new FcmClient(settings);
            }
            catch (Exception ex)
            {
                System.Diagnostics.Debug.WriteLine(ex.Message);
            }

**Comment by bytefish** [comment]
Could you show the Stacktrace of the Exception to see where exactely the Exception is thrown?

**Comment by bytefish** [comment]
With the information I am not able to reproduce the issue. Please reopen the ticket, if you can give any further informations about the issue and how to reproduce it.
