### ISSUE TITLE
Public fields in Message

### ISSUE THREAD

**Issue by Eirenarch** [bytefish/FcmSharp#27]
I am sorry to be that guy but I just can't help it. Is there a reason why Notification and Data are public fields instead of properties in the Message class?https://github.com/bytefish/FcmSharp/blob/master/FcmSharp/FcmSharp/Requests/Message.cs

**Comment by bytefish** [comment]
Oops! 😌 No, there is no reason. I didn't notice and it should be a property of course. I will fix it and make a new release of the libary! 

Thanks for bringing up the issue!

**Comment by bytefish** [comment]
They are properties now. I have released a new version 2.3.2 to NuGet containing the changes. Please reopen, if there are problems with the released version.
