### ISSUE TITLE
Specify single target

### ISSUE THREAD

**Issue by Polyterative** [bytefish/FcmSharp#32]
How can I send a noitification to a specific target device given a specific FCMToken?
How can I specify the target in the request?
Can I send a notification to a group of targets at the same time?

**Comment by bytefish** [comment]
You have to use the ``Token`` property for sending to a specific device. See the example at:

* https://github.com/bytefish/FcmSharp/blob/master/FcmSharp/Examples/CSharp/FcmSharp.Example/Program.cs

As far as I can see in the Firebase documents, there is no way to define Device Groups like in the Legacy Google Cloud Messaging API. Let me know if you find a way with the Firebase Cloud Messaging API, I don't know if it is possible.

**Comment by Polyterative** [comment]
Thanks
