### ISSUE TITLE
ApsAlert.cs missing subtitle properties

### ISSUE THREAD

**Issue by JeremyWeir** [bytefish/FcmSharp#33]
Hey, can you add the subtitle properties to the Alert class?

https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/generating_a_remote_notification#2943365

Thanks,
Jeremy

p.s. What is action-loc-key? I don't see it in the above doc

**Comment by bytefish** [comment]
Yes I can add it. The class is basically the same as in the Android Java SDK, maybe the ``action-loc-key`` has been in there, I didn't cross-check the Apple specs. 😅

**Comment by bytefish** [comment]
Apparently Google Implements this Spec, which has an ``action-loc-key`` and no subtitle Property.

* https://developer.apple.com/library/archive/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/PayloadKeyReference.html#//apple_ref/doc/uid/TP40008194-CH17-SW5

**Comment by bytefish** [comment]
I have made a 2.6.0-alpha pre-release, that includes the Subtitle for an Aps Alert:

* https://www.nuget.org/packages/FcmSharp/2.6.0-alpha

Could you please let me know, if it works as expected?

**Comment by bytefish** [comment]
@JeremyWeir Did you have a chance to test it?

**Comment by bytefish** [comment]
I will leave it in the ``2.6.0-alpha`` for now, because I am not able to test it myself.
