### ISSUE TITLE
Add Firebase Messaging Examples (Notifications, Data Messages, ...)

### ISSUE THREAD

**Issue by bytefish** [bytefish/FcmSharp#34]
Currently there is a lack of examples for the library. I am presenting a Data Message in the README, which doesn't show what most users want to do: Notifications. I have already added the simple Android ``quickstart-messaging`` to the Examples folder.

The README should be updated and Examples with the Android example should be shown, especially for Notifications.

**Comment by kehollin** [comment]
I'd love to help out, but struggling to find sufficient documentation on the semantics of the fields. If the Firebase docs were better this would be easier. It's also confusing for me how the different app states (foreground, background, killed) play into it, so I'm not 100% comfortable I'm getting all the messages. I'll come back and share what I learn. In the meantime, if you by chance have any working notifications that could be included in the read.me quickly I would really appreciate it!

Here's what I'm going to try first:

                    var pushMessage = new FcmMessage
                    {
                        ValidateOnly = false,
                        Message = new Message
                        {
                            Token = tokenParm.pvalue,
                            Topic = DEFAULT_TOPIC,
                            Notification = new Notification
                            {
                                Title = $"{appName}: tasks due",
                                Body = $"You have {tasksDue} tasks due, please open the app now to catch up!",
                            },
                            AndroidConfig = new AndroidConfig
                            {
                                Notification = new AndroidNotification
                                {
                                    Title = $"{appName}: tasks due",
                                    Body = $"You have {tasksDue} tasks due, please open the app now to catch up!",
                                    Sound = "default"
                                }
                            },
                            ApnsConfig = new ApnsConfig
                            {
                                Payload = new ApnsConfigPayload
                                {
                                    Aps = new Aps
                                    {
                                        Sound = "default",
                                        Badge = tasksDue
                                    }
                                }
                            }
                        }
                    };

**Comment by bytefish** [comment]
@kehollin Thanks for your efforts! The Firebase Docs are indeed a bit sparse on information, making it a little hard to build a rich set of samples. I will add an example for notifications later today!

**Comment by kehollin** [comment]
Thank you! I've updated the message initializer in my comment. I haven't
testing rigorously (i.e. app in foreground, background and killed states)
but will be doing so this coming week and will update the thread on GitHub
if I find any problems. One thing to note is that I'm sending to a specific
device ID, but including both AndroidConfig and ApnsConfig primarily
because I'm too lazy to code for different platforms, but it seems to be
allowed and harmless.

Kevin Hollingshead
Research Software Engineer

*Arizona State University*
*College of Health Solutions*
*School of Nutrition and Health Promotion*
602-615-9972 (cell)

**Comment by bytefish** [comment]
@kehollin Good job! 👍I would like to add (a slightly modified) example of your sample to the README, if you are OK with it? 😎

**Comment by kehollin** [comment]
Sure, maybe mask the device id too, no?

**Comment by bytefish** [comment]
It's early here, so maybe I am a bit slow. What do you mean by Masking the Device ID?

**Comment by bytefish** [comment]
@kehollin I have added an example for Notifications now, along with an Android sample project. The old tutorial was much too complicated, this one is a better Quickstart. Along the way I have also simplified reading the Service Account Key in the library, so one doesn't need to hardcode the project key in Code anymore. 

I have not integrated your example yet, but plan to do so. But I would need to write a longer documentation on it, because people will have questions I probably cannot answer... especially for the Apple iOS part, that I have not a lot of experience with.

If you find the time it would be great, if you could make a Pull Request to the README and put an example in the "Advanced" section. Maybe explaining all it in a Quickstart is too heave on Android / C# starters.

**Comment by bytefish** [comment]
Examples have been added for most of the Functions. The Android application makes a good start for Newcomers to Firebase and it is easy to get started with it. Everything else must be extracted from the docs, because I cannot make up examples for the entire API.
