### ISSUE TITLE
Sending an APNS Payload without a badge always resets the badge to 0 (Badge should be int? instead of int)

### ISSUE THREAD

**Issue by sir-boformer** [bytefish/FcmSharp#36]
https://github.com/bytefish/FcmSharp/blob/b8a4ebaf9076d41b0c1d72b64d64d6583a65f0cf/FcmSharp/FcmSharp/Requests/Aps.cs#L16

**Comment by bytefish** [comment]
Thanks for reporting. Feel free to make a Pull Request. 😎

**Comment by sir-boformer** [comment]
https://github.com/bytefish/FcmSharp/pull/37

**Comment by bytefish** [comment]
Good job!

I will release this fix in Version 2.6.0, but it will take a day due to work. 

I will leave this Ticket open.

**Comment by bytefish** [comment]
Sorry it took so long. I released ``2.6.0`` to NuGet, which will resolve this bug. Thanks again! 👍

**Comment by sir-boformer** [comment]
Compared to other open source projects, this was pretty fast ;)

**Comment by sir-boformer** [comment]
@bytefish Actually, it seems like version 2.6.0-alpha does not contain the change:

![grafik](https://user-images.githubusercontent.com/22688477/47036321-8dcd6c00-d17c-11e8-818d-3686cbdb7320.png)

**Comment by bytefish** [comment]
Correct! It is published, but indexing can take up to an hour. I thought you are not that fast with checking the package. 🤗 😳
