### ISSUE TITLE
Add Sound property to Notification class .

### ISSUE THREAD

**Issue by MohBrkat** [bytefish/FcmSharp#39]

**Comment by MohBrkat** [comment]
yea , thanks , i think you need to document the library better. But it is awesome and I appreciate your work.
I thought it doesn’t exist and thought this is something else , but it is worked , thats why i closed the issue .

**Comment by bytefish** [comment]
Great it is working! Yes it needs better documentation. I have already opened a Ticket #34 for better documentation, but I didn't have any time yet.
