### ISSUE TITLE
Using FcmSharp with asp.net web api

### ISSUE THREAD

**Issue by tickerman** [bytefish/FcmSharp#41]
hi
thank you for the great work you have done.
i used it in windows forms, xamarin forms and c# console app and everything works perfect.

but i want to use it in my web api and it just doesnt work and i dont know whats wrong.
I set the service account key build action to Embed Resource and Always copy ... is this right?

please guide.

thank you again.

**Comment by bytefish** [comment]
Why not read it from a File, that you put somewhere in the File System?

**Comment by tickerman** [comment]
I just tried it...
here is what i get:
 Could not Read Credentials. (Reason = File Does Not Exist, FileName = '/serviceresx/servacc.json')

i think i just dont know how to address it properly or maybe it needs some permissions i dont know.

**Comment by tickerman** [comment]
Thank you very muchhhh ,
lol I just used  HttpContext.Current.Server.MapPath to address the file and it worked great.

thank you again for the great job you have done.

**Comment by bytefish** [comment]
@tickerman Great you figured it out. Good luck with your project!
