### ISSUE TITLE
topic usage in Android 5.1 or lower

### ISSUE THREAD

**Issue by tickerman** [bytefish/FcmSharp#43]
Hi and Thank you again 

I'm using your great plugin to send notifications to my mobile Applications(Xamarin Forms) from my web service(asp.net).
both Client and Admin Applications are using the same firebase App but each subscribes to the related topics. 
after testing the app in different devices with different Android versions I found that in Android 5.1 ( all versions below 6.0 ) it wont matter in which topic you subscribe , it receives and shows all notifications from all topics. so the user's App will show Admins Notifications too...

I think eventually I'll have to create different Firebase Apps to solve this problem but I wanted to check with you first and ask if there is something Im doing wrong.

Thank you very very much indeed again

**Comment by bytefish** [comment]
This doesn't sound right. Only the devices registered to the Topic should receive the notification. Maybe you are using a simulator, that shares the Device Identifier and that's ehy it gets all notifications? Maybe you can ask on the Firebase Issue tracker with a little sample to reproduce the issue?

**Comment by bytefish** [comment]
This is really weird. Is there any way to introspect the device registrations with the Firebase Admin Console? I didn't use the website, but I think you can also send Notifications from there.
