### ISSUE TITLE
Proxy server issues

### ISSUE THREAD

**Issue by kdlslyv** [bytefish/FcmSharp#44]
Hi,

First of all, it's a neat and well done library. Thank you for that.

Kind of an edge-case issue nowadays, but still relevant in some environments: If you want to send a notification via FcmSharp over a proxy server, it's partially messed up due to how the short-lived access tokens are obtained. 

By modifying the FcmClient constructor, you can set a proxy server manually like this:

` 
var fcmClient = new FcmClient(_fcmClientSettings, JsonSerializer.Default, new FcmHttpClient(_fcmClientSettings, new ConfigurableHttpClient(new ConfigurableMessageHandler(new HttpClientHandler()
            {
                UseProxy = true,
                Proxy = _proxy,
            })), JsonSerializer.Default));
`

This however only works the for actual request - I haven't found a way to apply it to requests that happen rather automatically e.g. for the credentials. 
This request then times out and basically it won't work.

Only when modifying the `CreateServiceAccountCredential` method by using a custom `ServiceAccountCredential.Initializer` we can set a different `HttpClientFactory` to make the requests via a proxy work.

It works but right now it's not quite what I would envision for when submitting a pull request though - I created the initializer and copied the properties from the `GoogleCredential` as `ServiceAccountCredential`. 

Sadly when using .net Core it's also quite broken trying to set a DefaultProxy for requests like these.

Would you accept a pull request allowing to set HttpClientFactory for the ServiceAccountCredentials? (I'd put it in FcmClientSettings)

Kind regards

**Comment by bytefish** [comment]
Yes. Please make a Pull Request so we can iterate on it!

**Comment by bytefish** [comment]
First of all thanks for the issue. I didn't think about proxies, when obtaining Tokens. 😖 This is indeed a flaw and both, the HTTP Client inside FcmClient and from Google should be configurable.

I am thinking about the best way to approach it. Is it possible to pass the ``HttpClientFactory`` directly into the FcmClient implementation or should it be accessible from the FcmClientSettings? Or maybe pass an ``Action`` into it? 🤨

I wonder if it is really necessary to extend the interface. 

Not that it hurts too much, I am just thinking out loud.

**Comment by bytefish** [comment]
Uh, I was under the assumption, that ``Initialize(ConfigurableHttpClient httpClient)`` in the ``ServiceAccountCredential`` class overrides the ``HttpClient`` completely. But it only adds the message handlers:

![image](https://user-images.githubusercontent.com/239373/48658587-ed04f180-ea44-11e8-9da9-2868b8f3e4f2.png)

**Comment by bytefish** [comment]
Do you think changing the creation of the ``ServiceAccountCredential`` to something like this would do the job?

```csharp
private ServiceAccountCredential CreateServiceAccountCredential(HttpClientFactory httpClientFactory, IFcmClientSettings settings)
{
    var serviceAccountCredential = GoogleCredential.FromJson(settings.Credentials)
        // We need the Messaging Scope:
        .CreateScoped("https://www.googleapis.com/auth/firebase.messaging")
        // Cast to the ServiceAccountCredential:
        .UnderlyingCredential as ServiceAccountCredential;

    if (serviceAccountCredential == null)
    {
        throw new Exception($"Error creating ServiceAccountCredential from JSON File {settings.Credentials}");
    }

    var initializer = new ServiceAccountCredential.Initializer(serviceAccountCredential.Id, serviceAccountCredential.TokenServerUrl)
    {
        User = serviceAccountCredential.User,
        AccessMethod = serviceAccountCredential.AccessMethod,
        Clock = serviceAccountCredential.Clock,
        Key = serviceAccountCredential.Key,
        Scopes = serviceAccountCredential.Scopes,
        HttpClientFactory = httpClientFactory
    };

    return new ServiceAccountCredential(initializer);
}
```

**Comment by bytefish** [comment]
Great, thanks for the feedback! 😎 I will create an example for passing in Proxy Settings into the Client and add it to the README. Then I am going to release the library as 2.8.0. I don't think many people have overridden the ``FcmHttpClient`` so I am not regarding this as a Major Breaking change.

**Comment by bytefish** [comment]
OK! I released it to NuGet. Please give it a try and let me know, if you are now able to use the Proxy Server correctly. Please reopen the ticket, if the error persists.

**Comment by kdlslyv** [comment]
No further errors ever came up so far, so I suppose it supports this case correctly.

**Comment by bytefish** [comment]
Thanks for the feedback. 🤜🤛
