### ISSUE TITLE
Suggestion: For next major version, split into two assemblies interface & implementation

### ISSUE THREAD

**Issue by paulhickman-a365** [bytefish/FcmSharp#45]
It would be an improvement to split this project into two assemblies, one with the enums/models/exceptions/interfaces (e.g. FcmSharp.Primitives) and one with the implementation classes. 

That way the primitives assembly wouldn't need to take a dependency on Newtonsoft or Google Apis, which means these only need to be referenced from the top-level assembly of the calling application rather than every assembly that references one of the types exposed by FcmSharp.

It would require the JsonProperty and JsonConverter attributes to be removed from the models and instead configured in the serializer settings - something like:
````
new JsonSerializerSettings {
    ContractResolver = new DefaultContractResolver
    {
        NamingStrategy =new SnakeCaseNamingStrategy(),                
    },
    Converters = new JsonConverter[] { new DurationFormatConverter(), new StringEnumConverter() }
};
````

You can use the default `StringEnumConverter` if you give the enum values the `EnumMember(Value= "UPPER_CASE_VERISON")` attribute which comes from System.Runtime.Serialization

The downside is it makes it harder for anyone passing in their own serializer but I'm not sure why that option is needed - the JSON format required is fixed by Google and you define the c# message objects in the library.

**Comment by bytefish** [comment]
@paulhickman-a365 Thanks for the issue! Yes, that's something I am also thinking of. When I implemented FcmJava I splitted the library into a Core Part (Model, Requests, Interfaces) and a Client Implementation, which was dependent on the HTTP Library.

This makes sense, but I thought it would be an overkill for FcmSharp. 

I will consider it for a 3.0, but I cannot promise a timeline right now. 😇

**Comment by bytefish** [comment]
@paulhickman-a365 I am sorry, but I won't split the library into two separate assemblies. I will never switch the implementation from the Google API Client and I guess few projects will do so. So if you need an abstraction, you probably can extract the Request / Response objects and abstract this library away.

Sorry!
