### ISSUE TITLE
AndroidNotification object is missing channel_id (new in Oreo)

### ISSUE THREAD

**Issue by kehollin** [bytefish/FcmSharp#49]
According to the docs, as of Android Oreo apps supposedly require a channel ID in the AndroidNotification section, see [docs](https://firebase.google.com/docs/reference/fcm/rest/v1/projects.messages). Oddly, my push notifications appear to be working even though I don't have a channel ID defined in the manifest either. I'm targeting API 28 (Pie), but I'm struggling to manage the new app icon badge so I wanted to confirm the channel.

**Comment by bytefish** [comment]
@kehollin Thanks for the notification. 🙏 I will update the Request model with the channel_id property and release a new version. 😎

**Comment by bytefish** [comment]
Released 2.8.2 with the ``channel_id``.
