### ISSUE TITLE
Why it crashes without a topic?

### ISSUE THREAD

**Issue by opcodewriter** [bytefish/FcmSharp#52]
The example in README shows using a topic:

                // The Message should be sent to the News Topic:
                var message = new FcmMessage()
                {
                    ValidateOnly = false,
                    Message = new Message
                    {
                        Topic = "news",
                        Notification = notification
                    }
                };

Without giving a topic, it crashes:
```

Unhandled Exception: System.AggregateException: One or more errors occurred. ---> FcmSharp.Exceptions.FcmMessageException: {
  "error": {
    "code": 400,
    "message": "Recipient of the message is not set.",
    "errors": [
      {
        "message": "Recipient of the message is not set.",
        "domain": "global",
        "reason": "badRequest"
      }
    ],
    "status": "INVALID_ARGUMENT"
  }
}
```

**Comment by bytefish** [comment]
You need to set either a topic, target or condition for sending a message. This is also stated in your error message: ``"message": "Recipient of the message is not set.",``. 

For requires fields, please see the protocol documentation at: https://firebase.google.com/docs/reference/fcm/rest/v1/projects.messages.

**Comment by opcodewriter** [comment]
@bytefish Thanks. 

I don't understand why a **token**, or a **topic** or a **condition** is required. FCM has a testing page and you can target an app.  In FcmSharp, can this be done with the setting the property `AndroidConfig` on `Message`? Something like:

```
m.AndroidConfig = new AndroidConfig() 
{
   RestrictedPackageName  = "com.myapp"
};

```
Should this eliminate the need to set a topic/token/condition? I haven't yet tried it...

**Comment by bytefish** [comment]
I really don't know. As far as I know one of these had to be set. I don't know if this has changed by now. 🤔 Please let me know about your experiments.

**Comment by opcodewriter** [comment]
I'm pretty sure FCM allows sending push notifications without topic/token/conditoin... I just need to see how
