### ISSUE TITLE
"Not a valid FCM token" error - what is the correct format?

### ISSUE THREAD

**Issue by jameslavery** [bytefish/FcmSharp#54]
I'm getting this error when sending a message:

> {
>   "error": {
>     "code": 400,
>     "message": "The registration token is not a valid FCM registration token",
>     "errors": [
>       {
>         "message": "The registration token is not a valid FCM registration token",
>         "domain": "global",
>         "reason": "badRequest"
>       }
>     ],
>     "status": "INVALID_ARGUMENT"
>   }
> }

I'm capturing the token from debug output, and am using the literal string:

> <d9b6386b  c15845a2 04490455 a20ea3c4 bbcd1fbf c934b11e c369a9b4 e3c1e976>

for the Token.

Is this the correct format to send as the Token, or should I be formatting it differently?

Could I also be getting this error if the Token has expired or is not actually associated with my FCM Project?

**Comment by bytefish** [comment]
@jameslavery The Registration Token doesn't look right. A registration token for a device usually looks something like this ``fkBQTHxKKhs:AP91bHuEedxM4xFAUn0z ... JKZS``.

**Comment by jameslavery** [comment]
Thanks - yes I found that I was using the APNS token. I have now worked out how to get the FCM token and it's all working.

Sent from my phone. Apologies for brevity and possible auto-correct quirks.

________________________________
