### ISSUE TITLE
FCMClient dispose wrong?

### ISSUE THREAD

**Issue by Hagerino** [bytefish/FcmSharp#57]
Hello, 

in the past there where some issues with the usage of httpclient. Although it implements IDisposable it actually should be reused and not be disposed, otherwise you would get socketexceptions . For that reason Microsoft implemented the new HttpClientFactory to ensure the proper usage. See here:

https://docs.microsoft.com/en-us/dotnet/standard/microservices-architecture/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests

https://aspnetmonsters.com/2016/08/2016-08-27-httpclientwrong/

I glanced through your code and seems like you are using httpClient internally. In that case disposing the FCMClient like you do it in your example would be wrong and would lead to issues. Can you elaborate on that?

**Comment by bytefish** [comment]
A single HttpClient instance is used for the Lifetime of the FcmClient Instance. The HttpClient is *not* disposed for every requests. I cannot see how this can lead to Socket Exhaustion.

**Comment by Hagerino** [comment]
Thank you for your reply. The problem is that instantiating and disposing one FcmClient for each request means that you are instantiating and disposing one HttpClient for each request, which leads to the socketissues. So FcmClient shouldn't be used in a using statement like the HttpClient, but your example is encouraging the wrong usage and should ideally show the right way to use it.

**Comment by bytefish** [comment]
As a quick win, I will add a note in the README, that states how to correctly use it. For a later version the changes using a HttpClientFactory could be done. Do the posts equally apply to .NET Framework 4.5?

Thanks for your ideas!

**Comment by Hagerino** [comment]
I'm not sure if they equally apply, but i have another question(I'm sorry). So if i don't expose the fcmclient, can you guarantee that there is no further unmanaged memory allocation other than that what the httpclient is doing, which would lead to a memoryleak if i don't expose the fcmclient?

**Comment by bytefish** [comment]
No need to be sorry. It's hard to guarantee something, when I am using other dependencies to handle the Token generation and exponential retries. I didn't observe any memory leaks and there is no related issue yet.

**Comment by bytefish** [comment]
The thing is, that I am already using a HttpClientFactory abstraction used by the Google APIs. It is probably sufficient to move the client creation somewhere else and completely dismiss the HttpClient disposing.

**Comment by Hagerino** [comment]
So i guess the best thing to do at the moment is to create an instance, reuse it and dispose it after a certain amount of requests and/or after a certain amount of time and then replace it with a fresh one.

**Comment by bytefish** [comment]
Do you think the added section is clear enough? Sorry it took so long, so much work to do.

**Comment by bytefish** [comment]
I am closing this issue. I accept, that when the FcmClient is used in a "wrong" way it can lead to SocketExhaustion problems due to the HttpClient being disposed. I think the README now clearly states the problem to the users of the library.

But I really don't want to change the underlying behavior and introduce additional complexity into the library. If the HttpClientFactory works with .NET 4.5 I would be happy to change it. It's just I don't have much time to implement and maintain this approach myself and I would probably introduce bugs.
