### ISSUE TITLE
Adding this as a package creates bad references to old System.Http 

### ISSUE THREAD

**Issue by markalanevans** [bytefish/FcmSharp#6]
After adding this package, the project now has references in the config file like

```
<Reference Include="System.Net.Http, Version=4.1.1.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL">
      <HintPath>..\packages\System.Net.Http.4.3.2\lib\net46\System.Net.Http.dll</HintPath>
      <SpecificVersion>False</SpecificVersion>
      <Private>True</Private>
    </Reference>
```

The versions are off and it breaks the app from running. 

Any idea why?

**Comment by bytefish** [comment]
Not really. The dependencies in NuGet (if you look at Dependencies on https://www.nuget.org/packages/FcmSharp/2.1.0) look OK to me. 🤔 I will take a look on a fresh project on the weekend.

**Comment by bytefish** [comment]
I indeed reference the ``System.Net.Http`` for .NET 4.5: 

* https://github.com/bytefish/FcmSharp/blob/master/FcmSharp/FcmSharp/FcmSharp.csproj#L32

Do you think this causes the problem? It didn't cause a problem to date, but maybe NuGet has changed or VS Tooling in how to obtain packages? 🤔

**Comment by markalanevans** [comment]
@bytefish to resolve this, i installed each of your dependencies separately and then i installed your package. I don't understand Nuget well enough to know why there was an issue but I tried it multiple times and this was the only thing that worked.

Today i'll be wrapping FcmSharp with a service class and start testing it out. Excited to use this. Out of all the existing dotnet c# packages yours is the only one I could find that uses the V1 api, everyone else uses the legacy apis, you have a real shot at gaining momentum with this package.

These were the other packages I looked at:

* https://github.com/angelobelchior/FCM.Net
* https://github.com/tiagomtotti/firebaseNet
* https://github.com/UrimKurtishi/Firebase.NET

**Comment by bytefish** [comment]
Thanks for letting me know. I will keep this issue open, until I have checked it myself.

**Comment by bytefish** [comment]
This is an interesting discussion on the very same issue:

* https://github.com/IdentityModel/IdentityModel2/issues/76

**Comment by bytefish** [comment]
I have modified the Dependencies and hope this fixes it. I decided to use the Framework Assembly reference for ``net46`` targets. It is what Microsoft uses in _most_ of its SDKs on NuGet. Let me know if the problem comes back again, and reopen this ticket. 👍

**Comment by leastprivilege** [comment]
feel free to add to the discussion 

https://twitter.com/leastprivilege/status/996686174952546309

**Comment by bytefish** [comment]
@leastprivilege I would, but I don't have a Twitter handle. You can see, that I was even reading through various Microsoft SDK sources and didn't find a consistent way Microsoft includes the ``System.Net.Http`` reference. 😥

**Comment by bytefish** [comment]
@markalanevans I just created a 4.6.1 project myself. And though I have referenced the Framework System.Net.Http it still creates a reference, due to a Google Library having a dependency on the NuGet System.Net.Http. I hope the next Visual Studio Updates resolve this Tooling problem.
