### ISSUE TITLE
Push notification will not be shown in 'Cloud Messaging'

### ISSUE THREAD

**Issue by EnricoWuestenberg** [bytefish/FcmSharp#61]
I can send notifications via topic to device. But, this messages are not displayed in 'Cloud Messaging' overview. Only messages i send from there.

Example: "Test02"

https://console.firebase.google.com/project/{project_id}/notification

![grafik](https://user-images.githubusercontent.com/32926746/55730377-513a4900-5a18-11e9-95e2-92d2292a7a25.png)

**Comment by bytefish** [comment]
I am sorry, but this is out of my scope. If the message is successfully received, then the library works as expected. I am not sure, what's displayed in the Cloud Messaging Console and there is no information on what one should expect to see there.
