### ISSUE TITLE
is not sending any messages. this  screen output

### ISSUE THREAD

**Issue by vlknkc** [bytefish/FcmSharp#8]
Message ID = projects/mesajgonderimi/messages/8572269732777546645

not notification any messages
c# settings
 var settings = FileBasedFcmClientSettings.CreateFromFile("mesajgonderimi", @"C:\mesajgonderimi-firebase-adminsdk-ejvii-13b684eb0a.json");

where is the error help
How we can send notifications to one device at a time

thank u

**Comment by bytefish** [comment]
If you cannot send the message, then an exception should be thrown or the message response contains an error. What is the content in there?

**Comment by vlknkc** [comment]
thanks await

Would you attach a sample code for single device sending

**Comment by bytefish** [comment]
I have just tested it. It works. I am currently writing a blog post and a full end-to-end example to show how to send messages to specific devices.

**Comment by bytefish** [comment]
This should help you:

* [https://bytefish.de/blog/fcmsharp_getting_started/](https://bytefish.de/blog/fcmsharp_getting_started/)
