### ISSUE TITLE
FcmSharp.Requests.Notification missing fields

### ISSUE THREAD

**Issue by Extentsoftware** [bytefish/FcmSharp#9]
Hi 

With reference to https://firebase.google.com/docs/cloud-messaging/http-server-ref#notification-payload-support would it be possible to add a "sound" property to the FcmSharp.Requests.Notification message?

**Comment by bytefish** [comment]
FcmSharp supports two protocols. The old versions below 2.0 use the Legacy HTTP API you are refering to. The versions from 2.0 on are based on the new v1 protocol (https://firebase.google.com/docs/reference/fcm/rest/v1/projects.messages), which has objects like ``AndroidNotification``:  https://firebase.google.com/docs/reference/fcm/rest/v1/projects.messages#AndroidNotification. This object contains the ``sound`` property.
